name: frame_Translate
description: "Connects to Frame and streams audio from its microphone, which is sent through a local (on Host device) vosk speech-to-text engine, and displays the streaming text on the Frame display."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  record: ^5.0.5
  buffered_list_stream: ^1.3.0
  flutter_blue_plus: ^1.32.11
  logging: ^1.2.0
  speech_to_text: ^6.6.2  # or latest version
  http: ^0.13.3
  flutter_foreground_task: ^3.10.0
  permission_handler: ^9.2.0
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/frame_app.lua
